name: rentcarapp
description: "Rent a Car by Hendra"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.0.0
  meta: ^1.10.0
  equatable: ^2.0.3
  uuid: ^4.3.3
  http: ^1.2.0
  sqflite: ^2.2.4+1
  path: ^1.8.3
  path_provider: ^2.0.11
  flutter_svg: ^2.0.0+1
  image_picker: ^1.0.7
  dio: ^5.4.0
  intl: ^0.19.0
  flutter_launcher_icons: ^0.13.1
  dropdown_search: ^5.0.6
  checkbox_grouped: ^2.0.0
  accordion: ^2.6.0
  expansion_tile_card: ^3.0.0
  flex_color_scheme: ^7.3.1
  grouped_list: ^5.1.2
  flutter_chat_ui: ^1.6.12
  file_picker: ^8.0.0+1
  mime: ^1.0.5
  open_filex: ^4.4.0
  flutter_chat_types: ^3.6.2
  share_it: ^0.7.0
  flutter_file_downloader: ^1.2.1
  percent_indicator: ^4.0.1
  connectivity_plus: ^6.0.2
  const_date_time: ^1.1.0
  foundation: ^0.0.5
  collection: ^1.18.0
  flutter_speed_dial: ^7.0.0
  flutter_slidable: ^3.1.0
  date_field: ^5.0.1
  string_validator: ^1.0.2
  jiffy: ^6.3.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  google_fonts: ^6.1.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/    

flutter_launcher_icons:
  image_path: "assets/images/logo_launcher.png"
  android: true
  ios: true  
  remove_alpha_ios: true
  background_color_ios: "#ffffff"
  min_sdk_android: 21 # android min sdk min:16, default 21